#if os(tvOS)
    import AVKit
    import DesignSystem
    import JellyfinKit
    import SwiftUI
    import UIKit

    /// The tvOS Up Next card, presented by AVKit as an `AVContentProposal`
    /// (#186).
    ///
    /// tvOS has no *default* content-proposal card: `AVPlayerViewController`
    /// only presents a proposal if it has a `contentProposalViewController`
    /// (per Apple's "Presenting Content Proposals in tvOS"). This is that view
    /// controller — it hosts a themed SwiftUI card and, because AVKit presents
    /// it inside the player's own hierarchy, its buttons are focusable, which
    /// the old SwiftUI sibling overlay never was.
    ///
    /// It is installed *once* on the player view controller (in
    /// `makeUIViewController`, a main-actor context) rather than assigned from
    /// the `shouldPresent` delegate: that delegate's isolation differs between
    /// SDKs, and touching a main-actor property there fails to compile under
    /// one toolchain or the other. The card's contents are read from AVKit's
    /// per-presentation `contentProposal` each time it appears.
    ///
    /// This card is a *prompt only* — it does not run an autoplay countdown.
    /// "Do nothing" autoplay is owned by `PlaybackViewModel.handlePlaybackEnded`
    /// (post-roll, like before #186), so it happens even if this card is never
    /// seen. The card carries a single button — dismissal is the remote's back
    /// button, the established pattern — so there are exactly two outcomes:
    /// - **Play Next** → `.accept` → delegate `didAccept` → `playNextEpisodeNow()`.
    /// - **Menu/back press** → AVKit dismisses the card itself with `.defer`
    ///   semantics (resume the current item; `.reject` would instead dismiss
    ///   the whole player), and *no* code path in this file or the delegate
    ///   runs. The episode plays out and post-roll autoplay advances. Per
    ///   `AVContentProposalViewController.h` a deferred proposal is still
    ///   pending: it stays attached to the item and AVKit re-presents it when
    ///   the item ends — which is exactly when post-roll autoplay swaps in the
    ///   next episode on the same player, stranding the stale card on top of
    ///   it. `viewWillDisappear` catches this undecided dismissal and fires
    ///   `onDismissWithoutDecision` so the proposal can be detached (keeping
    ///   the queued episode — deferring is not declining).
    /// The app's `AVContentProposal`, carrying the structured fields the base
    /// class has no slot for (its only text is `title`).
    ///
    /// AVKit hands the *same instance* back to the card: `nextContentProposal`
    /// and `contentProposal` are both `strong` properties, so nothing on this
    /// path copies. The `as?` read below degrades gracefully regardless — a
    /// base-class proposal just renders without an eyebrow. This also avoids
    /// `AVMetadataItem`'s accessors, whose sync forms are deprecated and whose
    /// async `load(.stringValue)` would let the card render before its
    /// eyebrow arrived.
    final class UpNextContentProposal: AVContentProposal {
        /// The compact season/episode code ("S2E4"), the card's eyebrow line
        let episodeCode: String?

        init(
            contentTimeForTransition: CMTime,
            title: String,
            previewImage: UIImage?,
            episodeCode: String?,
        ) {
            self.episodeCode = episodeCode
            super.init(
                contentTimeForTransition: contentTimeForTransition,
                title: title,
                previewImage: previewImage,
            )
        }
    }

    final class UpNextProposalViewController: AVContentProposalViewController {
        private let onDismissWithoutDecision: @MainActor () -> Void
        private var host: UIHostingController<AnyView>?

        /// Set by Play Next before it dismisses. Still false in
        /// `viewWillDisappear` means AVKit initiated the dismissal: a Menu
        /// press (undecided defer — the case that must detach the proposal)
        /// or the automatic-acceptance countdown (where the spurious detach
        /// is harmless: the accepted flow discards the item anyway).
        private var decisionMade = false

        init(onDismissWithoutDecision: @escaping @MainActor () -> Void) {
            self.onDismissWithoutDecision = onDismissWithoutDecision
            super.init(nibName: nil, bundle: nil)
        }

        /// `dynamic` (Xcode's autogenerated spelling) is deliberately absent:
        /// the previews' dynamic-replacement compile cannot thunk a `dynamic`
        /// initializer and fails the whole file's preview build.
        @available(*, unavailable)
        @MainActor required init?(coder _: NSCoder) {
            fatalError("init(coder:) is not supported")
        }

        override func viewWillAppear(_ animated: Bool) {
            super.viewWillAppear(animated)
            // AVKit reuses this instance across presentations, so every
            // appearance starts undecided.
            decisionMade = false
            // AVKit sets `contentProposal` to the item being presented before
            // this fires, so the card reflects the current next episode.
            rebuildCard(from: contentProposal)
        }

        override func viewWillDisappear(_ animated: Bool) {
            super.viewWillDisappear(animated)
            if !decisionMade {
                onDismissWithoutDecision()
            }
        }

        private func rebuildCard(from proposal: AVContentProposal?) {
            let card = UpNextProposalCard(
                eyebrow: (proposal as? UpNextContentProposal)?.episodeCode,
                title: proposal?.title ?? String(localized: "Up Next"),
                previewImage: proposal?.previewImage.map(Image.init(uiImage:)),
                onPlayNext: { [weak self] in
                    self?.decisionMade = true
                    self?.dismissContentProposal(for: .accept, animated: true)
                },
            )
            let root = AnyView(card.withThemeEnvironment())

            if let host {
                host.rootView = root
                return
            }
            let host = UIHostingController(rootView: root)
            host.view.backgroundColor = .clear
            addChild(host)
            host.view.translatesAutoresizingMaskIntoConstraints = false
            view.addSubview(host.view)
            NSLayoutConstraint.activate([
                host.view.leadingAnchor.constraint(equalTo: view.leadingAnchor),
                host.view.trailingAnchor.constraint(equalTo: view.trailingAnchor),
                host.view.topAnchor.constraint(equalTo: view.topAnchor),
                host.view.bottomAnchor.constraint(equalTo: view.bottomAnchor),
            ])
            host.didMove(toParent: self)
            self.host = host
        }
    }

    /// Proposes at most `maxWidth` to its child and adopts the child's
    /// resulting size — a *non-greedy* width cap.
    ///
    /// `frame(maxWidth:)` cannot express this: flexible frames are greedy and
    /// claim the whole cap whenever the incoming proposal allows, which held
    /// the title row at a constant 620pt and left a title-length-dependent
    /// band of empty column between the text and the card's trailing edge.
    /// With this layout a short title's row is exactly the text's width,
    /// while a long one still wraps (and then truncates) at the cap.
    private struct WidthCapLayout: Layout {
        let maxWidth: CGFloat

        func sizeThatFits(proposal: ProposedViewSize, subviews: Subviews, cache _: inout ()) -> CGSize {
            guard let subview = subviews.first else { return .zero }
            return subview.sizeThatFits(capped(proposal))
        }

        func placeSubviews(in bounds: CGRect, proposal: ProposedViewSize, subviews: Subviews, cache _: inout ()) {
            subviews.first?.place(at: bounds.origin, anchor: .topLeading, proposal: capped(proposal))
        }

        /// A nil (ideal-size) width probe is also capped, so the stack's
        /// sizing passes never measure the text at its unbounded single-line
        /// ideal.
        private func capped(_ proposal: ProposedViewSize) -> ProposedViewSize {
            var proposal = proposal
            proposal.width = proposal.width.map { min($0, maxWidth) } ?? maxWidth
            return proposal
        }
    }

    /// Themed contents of the tvOS Up Next proposal card.
    struct UpNextProposalCard: View {
        @Environment(\.theme) private var theme

        /// The season/episode code ("S2E4"), styled as its own eyebrow line
        /// rather than baked into the title string
        let eyebrow: String?
        let title: String
        let previewImage: Image?
        let onPlayNext: () -> Void

        var body: some View {
            HStack(alignment: .center, spacing: SpacingTokens.lg) {
                if let previewImage {
                    previewImage
                        .resizable()
                        .aspectRatio(contentMode: .fit)
                        .frame(maxWidth: 480, maxHeight: 270)
                        .clipShape(RoundedRectangle(cornerRadius: theme.cornerRadiusLarge))
                }

                // The title is width-capped so a long one wraps (letting the
                // two-line limit engage) instead of stretching the card across
                // the full screen — the HStack otherwise grows leftward from
                // its bottom-trailing anchor without bound.
                VStack(alignment: .leading, spacing: SpacingTokens.md) {
                    // The code and the title read as one lockup, so they sit
                    // tighter than the outer stack's rhythm
                    VStack(alignment: .leading, spacing: SpacingTokens.xxs) {
                        if let eyebrow {
                            Text(eyebrow)
                                .jsStyle(.caption)
                                .foregroundStyle(theme.secondary)
                        }

                        WidthCapLayout(maxWidth: 620) {
                            Text(title)
                                .jsStyle(.title)
                                .foregroundStyle(theme.primary)
                                .lineLimit(2)
                        }
                    }

                    // A lone button: dismissing the card is the remote's back
                    // button (dismiss, play out, autoplay) — a Cancel button
                    // duplicating that would just be an extra focus stop.
                    Button(action: onPlayNext) {
                        HStack(spacing: SpacingTokens.sm) {
                            Image(systemName: "play.fill")
                            Text("Play Next")
                        }
                        .jsStyle(.body).bold()
                    }
                    .glassButtonStyle(tint: theme.focusFill)
                }
            }
            .padding(SpacingTokens.xxl)
            .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .bottomTrailing)
        }
    }

    // MARK: - Previews

    /// Stand-in for a decoded episode still (previews have no network): a
    /// rendered 16:9 frame in the proportions real artwork arrives in, so the
    /// card lays out exactly as it does on device.
    private func previewStill() -> Image {
        let size = CGSize(width: 480, height: 270)
        return Image(uiImage: UIGraphicsImageRenderer(size: size).image { context in
            UIColor(red: 0.16, green: 0.2, blue: 0.3, alpha: 1).setFill()
            context.fill(CGRect(origin: .zero, size: size))
        })
    }

    /// The closing frames of the playing episode, which AVKit keeps on screen
    /// behind the proposal — placement only reads in that context.
    private let previewBackdrop = LinearGradient(
        colors: [Color(red: 0.05, green: 0.05, blue: 0.08), Color(red: 0.12, green: 0.1, blue: 0.16)],
        startPoint: .top,
        endPoint: .bottom,
    )

    #Preview("With artwork") {
        UpNextProposalCard(
            eyebrow: "S3E7",
            title: "Midnight Broadcast",
            previewImage: previewStill(),
            onPlayNext: {},
        )
        .background(previewBackdrop)
        .ignoresSafeArea()
        .withThemeEnvironment()
    }

    // Also the no-eyebrow state: an episode carrying no season/episode
    // numbers drops the line entirely rather than leaving a gap.
    #Preview("No artwork, long title") {
        UpNextProposalCard(
            eyebrow: nil,
            title: "The Uncommonly Long Episode Title That Wraps to a Second Line Before It Truncates",
            previewImage: nil,
            onPlayNext: {},
        )
        .background(previewBackdrop)
        .ignoresSafeArea()
        .withThemeEnvironment()
    }
#endif
